# Generated by Django 5.2.1 on 2025-06-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.JSONField(default=list)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_at', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.JSONField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.JSONField(default=list)),
                ('company_url_img', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
